### ISSUE TITLE
How to get the score on the test dataset for the tiles task?

### ISSUE THREAD

**Issue by baziotis** [google-research-datasets/tpu_graphs#10]
Running the following (note the `--test_mode` argument):
```
python tiles_train.py ... --test_mode=metrics
```
gives NaNs for the test dataset (in the `.jsonz` file)

**Comment by baziotis** [comment]
If it helps, [this line](https://github.com/google-research-datasets/tpu_graphs/blob/e3e7933824ac86c155ce5a7728cb2ca1c572c603/tpu_graphs/baselines/tiles/metrics.py#L57):
```
runtimes = graph.node_sets['config']['runtimes']
```
in `top_error_performance()` which is called [here](https://github.com/google-research-datasets/tpu_graphs/blob/e3e7933824ac86c155ce5a7728cb2ca1c572c603/tpu_graphs/baselines/tiles/train_lib.py#L172), gives a tensor of zeros all the time, and this seems to be why we get the NaNs.

**Comment by samihaija** [comment]
This is expected. We decided to remove the labels from the test files (everything has runtime of zero). You may either:

1. Submit your CSV to Kaggle, to get your test scores: kaggle.com/competitions/predict-ai-model-runtime
2. Use the validation set as-if it was the testing set. This way, the scores (= runtimes) are present and your evaluation metrics will not be NaN
