### ISSUE TITLE
Can't setup the environment for the program

### ISSUE THREAD

**Issue by yadhukrishnana** [google-research-datasets/tpu_graphs#6]
I have tried run the program in python using normal python interpreter 3.11, but unfortunately I couldn't load the package for tensorflow_gnn. It's showing an error while trying to install the pyarow. Can you please suggest the solution

ERROR: Could not build wheels for pyarrow, grpcio-tools, which is required to install pyproject.toml-based projects

ERROR: Failed building wheel for grpcio-tools
   ModuleNotFoundError: No module named 'cmake'
      error: command 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Scripts\\cmake.exe' failed with exit code 1       
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyarrow
  Building wheel for grpcio-tools (setup.py) ... error
  error: subprocess-exited-with-error

**Comment by FabienDaniel** [comment]
I had a similar issue with python 3.11 and couldn't make it work. Switching to python 3.10 works fine however.

**Comment by mangpo** [comment]
Yes, please use python 3.10. I'll update the instruction.
