### ISSUE TITLE
`tiles_evaluate.py` fails when evaluating `EarlyJoinSAGE` trained on toy data

### ISSUE THREAD

**Issue by baziotis** [google-research-datasets/tpu_graphs#8]
I first run this:
```
python tiles_train.py --model=EarlyJoinSAGE --toy_data=True
```
which creates a directory `model_<hash>` in `~/out/tpugraphs_tiles`. Then, running:
```
python tiles_evaluate.py --dirs ~/out/tpugraphs_tiles/model_<hash>
```
fails with:
```
  File ".../tpu_graphs/tiles_evaluate.py", line 114, in <module>
    app.run(main)
  File ".../anaconda3/envs/tpugraphs/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File ".../anaconda3/envs/tpugraphs/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File ".../tpu_graphs/tiles_evaluate.py", line 85, in main
    assert sv.shape == tv.shape
AssertionError
```
---
Note that it works if I train the same model on the full dataset.

**Comment by baziotis** [comment]
This happens with other model classes too. For example, `MLP` trained on toy data fails but works fine when trained on the full dataset.

**Comment by samihaija** [comment]
We will not fix this.

The data.py pipeline removed all constant features. When training on entire dataset, there are only a couple of always constant features. When training on toy data, there are a dozen of constant features on the sampled ("toy") examples. Therefore, the first layer of the model will have fewer input dimensions.

The purpose of `--toy_data` flag is to only run code (under development) as a "unit test" to check for typos, logical mistakes, etc, but not to train an actual model to evaluate (e.g., per benchmark on tiles data).
